timeout: 3600s

steps:

# SECURE DATA DATA OPS PROJECT

- id: "data-ops projects - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/$BRANCH_NAME/data-ops'
  ]

- id: "terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
  
- id: "data-ops project - destroy plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-destroy'
  ]

- id: "data-ops project - destroy all"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  args: [
  'destroy',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-auto-approve'
  ]
