timeout: 1800s

steps:

# SDE FOLDERS APPLY

- id: "folder init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  args: [
  'init',
  '-backend-config=bucket=${_BUCKET}',
  '-backend-config=prefix=${_PREFIX}/$BRANCH_NAME/folders'
  ]

- id: "terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME

- id: Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/folders'
  args: ['fmt',
    '-check'
    ]

- id: Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/folders'
  args: ['validate',
    '-no-color'
    ]

- id: "folders plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]

- id: "folders apply"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  args: [
  'apply',
  '-var-file=env/${_TFVARS_FILE}.tfvars',
  '-auto-approve'
  ]

