steps:

# PACKER PROJECT

- id: "terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  args: [
    'init',
    '-backend-config=bucket=${_BUCKET}',
    '-backend-config=prefix=${_PREFIX}/$BRANCH_NAME/image'
  ]

- id: "terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME

- id: Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['fmt',
    '-check'
    ]

- id: Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['validate',
    '-no-color'
    ]

- id: "terraform plan - turn off org policy"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-var=set_disable_sa_create=false',
  ]
      
- id: "terraform apply - turn off org policy"
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['apply',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-var=set_disable_sa_create=false',
    '-auto-approve'
  ]

- id: "terraform plan - turn on org policy"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]
      
- id: "terraform apply - turn on org policy"
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['apply',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
    '-auto-approve'
  ]

timeout: 3600s