timeout: 3600s

steps:

# --- Folder Heirarchy

- id: "folder store git branch"
  name: ubuntu
  entrypoint: bash
  args:
  - -c
  - |
      # save git branch to persistent volume: /workspace
      echo "Current branch name is $BRANCH_NAME"
      if [[ "$BRANCH_NAME" == test* ]] || [[ "$BRANCH_NAME" == test ]]; then
        branch=test
        echo "Branch Name is now $branch"
        echo $branch > /workspace/branch.txt
      elif [[ "$BRANCH_NAME" == main* ]] || [[ "$BRANCH_NAME" == main ]]; then
        branch=main
        echo "Branch Name is now $branch"
        echo $branch > /workspace/branch.txt
      fi

- id: "folder init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/folders
  

- id: "folder terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: folder Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/folders'
  args: ['fmt',
    '-check'
    ]

- id: folder Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/folders'
  args: ['validate',
    '-no-color'
    ]

- id: "folders plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/folders'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]

# --- Cloud Build Triggers


- id: "cb-triggers tf - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/cloudbuild-sde

- id: "cb-triggers terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: "cb-triggers terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/cloudbuild-sde'
  args: [
    'plan'
  ]

# --- Data Ingress

- id: "ingress project terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ingress'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/data-ingress

- id: "ingress project terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ingress'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: ingress project Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-ingress'
  args: ['fmt',
    '-check'
    ]

- id: ingress project Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-ingress'
  args: ['validate',
    '-no-color'
    ]

- id: "ingress project terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ingress'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]

# --- Imaging Project

- id: "image prj terraform init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/image

- id: "image prj terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: image prj Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['fmt',
    '-check'
    ]

- id: image prj Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/image'
  args: ['validate',
    '-no-color'
    ]

- id: "image prj terraform plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/image'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars',
  ]

# --- Data Ops

- id: "data-ops project - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/data-ops

- id: "data-ops projectterraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: data-ops projectTerraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-ops'
  args: ['fmt',
    '-check'
    ]

- id: data-ops projectTerraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-ops'
  args: ['validate',
    '-no-color'
    ]

- id: "data-ops project - first plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-ops'
  args: [
  'plan',
  '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]

# --- Data Lake

- id: "datalake project - init"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-lake'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform init -backend-config=bucket=${_BUCKET} -backend-config=prefix=${_PREFIX}/$(cat /workspace/branch.txt)/data-lake

- id: "datalake project terraform workspace"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-lake'
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
        terraform workspace select $(cat /workspace/branch.txt) || terraform workspace new $(cat /workspace/branch.txt)

- id: datalake project Terraform Format
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-lake'
  args: ['fmt',
    '-check'
    ]

- id: datalake project Terraform Validate
  name: 'hashicorp/terraform:${_TAG}'
  dir: 'environment/foundation/data-lake'
  args: ['validate',
    '-no-color'
    ]

- id: "datalake project - plan"
  name: hashicorp/terraform:${_TAG}
  dir: 'environment/foundation/data-lake'
  args: [
    'plan',
    '-var-file=env/${_TFVARS_FILE}.tfvars'
  ]